name: Deploy Static Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Replace placeholders with secrets
      run: |
        sed -i "s|__API_URL__|${{ secrets.API_URL }}|g" index.html
        sed -i "s|__API_TOKEN__|${{ secrets.API_TOKEN }}|g" index.html
        sed -i "s|__API_CLIENT_TOKEN__|${{ secrets.API_CLIENT_TOKEN }}|g" index.html

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: "/" # Root folder where index.html is located
        output_location: "/" # Root folder since there is no build
